"""create contact table

Revision ID: 89beb69094a8
Revises: 7952f2b2e389
Create Date: 2026-07-07 22:36:00.653616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89beb69094a8'
down_revision = '7952f2b2e389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
